name: Release

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: |
        GOOS=windows GOARCH=amd64 go build -o release_folder/psc-1.0.${{ github.run_number }}-windows-amd64.exe
        GOOS=darwin GOARCH=amd64 go build -o release_folder/psc-1.0.${{ github.run_number }}-darwin-amd64
        GOOS=darwin GOARCH=arm64 go build -o release_folder/psc-1.0.${{ github.run_number }}-darwin-arm64
        GOOS=linux GOARCH=amd64 go build -o release_folder/psc-1.0.${{ github.run_number }}-linux-amd64
        GOOS=linux GOARCH=arm64 go build -o release_folder/psc-1.0.${{ github.run_number }}-linux-arm64

    # commented, because it needs a real OpenAI API Key for running the test.
    # - name: Run Go Tests
    #   run: go test ./...

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.${{ github.run_number }}
        release_name: Release 1.0.${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Create tar.gz archive
      run: |
        tar -czf release_folder/psc-1.0.${{ github.run_number }}-darwin-amd64.tar.gz -C release_folder/ psc-1.0.${{ github.run_number }}-darwin-amd64
        tar -czf release_folder/psc-1.0.${{ github.run_number }}-darwin-arm64.tar.gz -C release_folder/ psc-1.0.${{ github.run_number }}-darwin-arm64
        tar -czf release_folder/psc-1.0.${{ github.run_number }}-linux-amd64.tar.gz -C release_folder/ psc-1.0.${{ github.run_number }}-linux-amd64
        tar -czf release_folder/psc-1.0.${{ github.run_number }}-linux-arm64.tar.gz -C release_folder/ psc-1.0.${{ github.run_number }}-linux-arm64
        tar -czf release_folder/psc-1.0.${{ github.run_number }}-windows-amd64.tar.gz -C release_folder/ psc-1.0.${{ github.run_number }}-windows-amd64.exe

    - name: Upload Release Assets (MacOS amd64)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: release_folder/psc-1.0.${{ github.run_number }}-darwin-amd64.tar.gz
        asset_name: psc-1.0.${{ github.run_number }}-darwin-amd64.tar.gz
        asset_content_type: application/gzip

    - name: Upload Release Assets (MacOS arm64)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: release_folder/psc-1.0.${{ github.run_number }}-darwin-arm64.tar.gz
        asset_name: psc-1.0.${{ github.run_number }}-darwin-arm64.tar.gz
        asset_content_type: application/gzip

    - name: Upload Release Assets (Linux amd64)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: release_folder/psc-1.0.${{ github.run_number }}-linux-amd64.tar.gz
        asset_name: psc-1.0.${{ github.run_number }}-linux-amd64.tar.gz
        asset_content_type: application/gzip

    - name: Upload Release Assets (Linux arm64)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: release_folder/psc-1.0.${{ github.run_number }}-linux-arm64.tar.gz
        asset_name: psc-1.0.${{ github.run_number }}-linux-arm64.tar.gz
        asset_content_type: application/gzip

    - name: Upload Release Assets (Windows amd64)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: release_folder/psc-1.0.${{ github.run_number }}-windows-amd64.tar.gz
        asset_name: psc-1.0.${{ github.run_number }}-windows-amd64.tar.gz
        asset_content_type: application/gzip
